In [1]:
import numpy as np

# Load all batches
X1 = np.load('X_train_batch_1.npy')
X2 = np.load('X_train_batch_2.npy')
X3 = np.load('X_train_batch_3.npy')
X4 = np.load('X_train_batch_4.npy')
X5 = np.load('X_train_batch_5.npy')


y1 = np.load('y_train_batch_1.npy')
y2 = np.load('y_train_batch_2.npy')
y3 = np.load('y_train_batch_3.npy')
y4 = np.load('y_train_batch_4.npy')
y5 = np.load('y_train_batch_5.npy')


# Combine
X_combined = np.concatenate([X1, X2, X3, X4, X5])  # Add more batches to list
y_combined = np.concatenate([y1, y2, y3, y4, y5])  # Add more batches to list

# Save combined dataset
np.save('X_train_final.npy', X_combined)
np.save('y_train_final.npy', y_combined)

print(f"Combined dataset: {X_combined.shape[0]:,} positions")

Combined dataset: 129,415 positions


In [2]:
import numpy as np

# Load the files
X = np.load('X_train_final.npy')
y = np.load('y_train_final.npy')

print("First 5 Boards and Best Moves:\n")

for i in range(5):
    # Combine channels to see the full board
    board = X[i][:,:,0] - X[i][:,:,1]
    
    print(f"Position {i+1}:")
    print(board)
    print(f"→ Best move: Column {y[i]}\n")

...

First 5 Boards and Best Moves:

Position 1:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1. -1.  1.  1.]]
→ Best move: Column 2

Position 2:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  1. -1.  1.]]
→ Best move: Column 3

Position 3:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  1. -1.]]
→ Best move: Column 3

Position 4:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  1. -1.]]
→ Best move: Column 3

Position 5:
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0. 

Ellipsis